server:
  port: 8080
spring:
#  profiles:
#    active: dev #????? dev ???? ??
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/examquestion?useUnicode=true&characterEncoding=utf8
    username: root
    password: qkr96#
  jpa:
    hibernate:
      ddl-auto: create  #create update
    properties:
      hibernate:
        show_sql: true #sql ??
        format_sql: true  #sql ? ?? ?? ???
        use_sql_comments: true #SIUD ? ?? ?? ??????
